# Generated by Django 2.2.16 on 2020-11-26 18:54

from django.db import migrations, models
import django.db.models.deletion

def add_surveys(apps, schema_editor):
    Survey = apps.get_model('survey', 'Survey')
    db_alias = schema_editor.connection.alias
    Survey.objects.using(db_alias).bulk_create([
        Survey(description='Industry digital skills'),
        Survey(description='individual digital skills')
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RunPython(add_surveys),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
            preserve_default=False,
        ),
    ]
